In [18]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.3.1'

In [3]:
df = pd.read_csv("car_fuel_efficiency.csv")

In [8]:
df.index

RangeIndex(start=0, stop=9704, step=1)

In [14]:
df.fuel_type.unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [24]:
df.count().isnull().sum()

np.int64(0)

In [35]:
df[df['origin']=='Asia'].fuel_efficiency_mpg.max()

np.float64(23.759122836520497)

In [36]:
df.horsepower.median()

np.float64(149.0)

In [63]:
df.horsepower.mode()[0]

np.float64(152.0)

In [65]:
df.horsepower.fillna(df.horsepower.mode()[0])

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [66]:
df.horsepower.median()

np.float64(152.0)

In [6]:
df_asia = df[df['origin']=='Asia']

In [26]:
df_asia = df[['vehicle_weight','model_year']]

In [27]:
X = np.array(df_asia.iloc[0:7])

In [28]:
X

array([[3413.43375861, 2003.        ],
       [3149.66493422, 2007.        ],
       [3079.03899737, 2018.        ],
       [2542.39240183, 2009.        ],
       [3460.87098999, 2009.        ],
       [2484.88398604, 2008.        ],
       [3006.54228722, 2012.        ]])

In [40]:
Xt = X.T

In [41]:

XTX = np.dot(Xt,X)

In [42]:
XTX

array([[64707732.45267162, 42471352.31816065],
       [42471352.31816065, 28264752.        ]])

In [43]:
invert_XTX = np.linalg.inv(XTX)

In [44]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [52]:
w = np.dot(invert_XTX, Xt)
w = np.dot(w, y)

In [53]:
w

array([0.07099685, 0.41931263])

In [55]:
np.sum(w).round(2)

np.float64(0.49)