In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1,2,3,4,5])

In [8]:
a[2] = 10

In [9]:
a

array([ 1,  2, 10,  4,  5])

In [11]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [13]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [17]:
n[0,1]

np.int64(2)

In [20]:
n[0]

array([1, 2, 3])

In [23]:
np.random.rand(5,2)

array([[0.64986924, 0.16603795],
       [0.45870309, 0.79870978],
       [0.06911007, 0.81165221],
       [0.42208659, 0.26055933],
       [0.42166091, 0.71041608]])

In [24]:
np.random.randn(5,2)

array([[-0.65528688, -0.27254528],
       [-0.78242791,  0.12906618],
       [-1.30293279,  0.13262472],
       [ 0.15110783, -0.28132495],
       [ 0.77529781, -1.12156948]])

In [25]:
np.random.randint(low=0, high=100, size=(5,2))

array([[93, 68],
       [72, 17],
       [67, 12],
       [67,  1],
       [50, 91]])