In [2]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1,2,3,4,5])

In [8]:
a[2] = 10

In [9]:
a

array([ 1,  2, 10,  4,  5])

In [11]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [13]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [17]:
n[0,1]

np.int64(2)

In [20]:
n[0]

array([1, 2, 3])

In [23]:
np.random.rand(5,2)

array([[0.64986924, 0.16603795],
       [0.45870309, 0.79870978],
       [0.06911007, 0.81165221],
       [0.42208659, 0.26055933],
       [0.42166091, 0.71041608]])

In [24]:
np.random.randn(5,2)

array([[-0.65528688, -0.27254528],
       [-0.78242791,  0.12906618],
       [-1.30293279,  0.13262472],
       [ 0.15110783, -0.28132495],
       [ 0.77529781, -1.12156948]])

In [25]:
np.random.randint(low=0, high=100, size=(5,2))

array([[93, 68],
       [72, 17],
       [67, 12],
       [67,  1],
       [50, 91]])

Vector by Vector Multiplication

In [3]:
u = np.array([2,4,5,6])
v = np.array([1,0,0,2])

def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    result =0.0
    for i in range (n):
        result= result + u[i] * v[i]
    return result


In [4]:
vector_vector_multiplication(u,v)

np.float64(14.0)

In [5]:
u.dot(v)

np.int64(14)

In [6]:
x = np.array([
   [2,4,5,6],
   [1,2,1,2],
   [3,1,2,1]
 ])

In [7]:
def matrix_vector_multiplication(x,v):
    assert x.shape[1]==v.shape[0]
    num_rows = x.shape[0]
    result = np.zeros(num_rows)
    for i in range (num_rows):
        result [i] = vector_vector_multiplication(x[i],v)
    return result



In [8]:
matrix_vector_multiplication(x,v)

array([14.,  5.,  5.])

In [9]:
x.dot(v)

array([14,  5,  5])

In [10]:
u = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [1,2,1,2],
    [3,1,2,1]
])

v = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0]
])

In [11]:
def matrix_matrix_multiplication(u,v):
    assert u.shape[1]==v.shape[0]
    num_rows =u.shape[0]
    num_columns = v.shape[1]
    result = np.zeros((num_rows,num_columns))
    for i in range (num_columns):
        vi = v[:,i]
        uvi = matrix_vector_multiplication(u,vi)
        result[:,i] = uvi
    return result

In [12]:
matrix_matrix_multiplication(u,v)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [13]:
u.dot(v)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [14]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])